# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-23 01:48
from __future__ import unicode_literals

import apps.first_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default=apps.first_app.models.set_default_dojo, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(default=apps.first_app.models.set_default_dojo, on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='first_app.Dojo'),
        ),
    ]
